# Generated by Django 5.0 on 2023-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_employee_email_address_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='files',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='ipType',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='isProgrammer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='settingJson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='showDuration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='showTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='smallInteger',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
