# Generated by Django 5.0 on 2023-12-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
